import { Inter } from "next/font/google";
import "./globals.css";
import MainSider from "@/components/MainSider/MainSider";
import JumpButton from "./jump/JumpButton";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div  style={{backgroundImage: 'url(https://i.ibb.co/26P93xn/bg.jpg)'}} className=" bg-bg-image bg-no-repeat bg-cover dark:bg-bg-image-dark bg-fixed font-font-rubik">
      <div className=" container mx-auto md:flex justify-center gap-6 ">
        <div className="md:w-1/3 border  ">
          <MainSider />
        </div>
        <div className=" md:w-2/3 border md:py-20 space-y-2 flex flex-col">
            <Navbar></Navbar>
          {children}
          <JumpButton></JumpButton>
        </div>
      </div>
    </div>
        </body>
    </html>
  );
}
